# Generated by Django 4.2 on 2023-05-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Rooms & Apartments', 'Rooms & Apartments'), ('Food & Restaurant', 'Food & Restaurant'), ('Spa & Fitness', 'Spa & Fitness'), ('Sports & Gaming', 'Sports & Gaming'), ('Event & Party', 'Events & Party'), ('GYM & Yoga', 'GYM & Yoga')], max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
