# Generated by Django 4.2 on 2023-05-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_category_alter_products_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('profession', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Reviews_images')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
